language: node_js
node_js:
- 8
- 7
- 6
deploy:
  provider: npm
  email: caiobsouza@hotmail.com
  api_key:
    secure: Kz30QrOL4nRXVL2YG8bsu7IeN1/rHhe4Bqcih+Inee74IPUotm7u44RnxhCxB8UxlMTTTCTqNjNFaqqfjF3Nokk3TkHH/8FYg2OX81U/ybwW7qQ+gPMLQVUtG9nLccpOylASorwpbyW4VkX3XoFjpDDMwS8zXimNDxd8Nn7oESq64CTMEUfcECC/eb3hL2BrPQjg1FD2pKpSA/qop6vLVzdP1IG9Q64qk6axI8jQ3c1Ek1FEThiUtyrYG3EUhyDTU2E7pHqTGiUhnU8j/9JO5HceWwNYwujR40TVxv43dg9X/d3o50ZiXwnWJs9oM9sDoFrWU2WIYWb6T7bu0zKhQFMUsiuL9vSoEX//88AWL/uudV5Rj4pWHDW0u3OUtN4FTg3U84dEaJJmwzj99orVQAISIdpdqkkdspK7o8O+eF2TXFLoaR3MwQpanH3PJ1vQNLoSFOalGfVjqekp8bYDq2qCye/TbAt4FKI7eCkxByYWCpVXB5sl+lJ8elFA88UX2fdf1Xc54tYleOQIZZ+Hp3FoQLXUtVJwzhIB/7hlbyt5cXuF3wwuqYjjFGOdEqOoz9t5FfSPBGiy/q4RE47jXXhg0pQs1Vj5MJPb2oKvcmIfwaPmkAekvM1J/i9J9fcPBEKuZu7RBfjlth+bkiSfyYG8gwCSUcu1SUpLUEIVCr8=
  on:
    repo: caiobsouza/ts-node-api
